[package]
name = "gb2idb"
version = "0.1.0"
authors = ["Felix Konstantin Maurer <maufl@maufl.de>"]

[dependencies]
clap = "2"
rusqlite = "0.13"
reqwest = "0.8"
log = "0.4"
env_logger = "0.5"
itertools = "0.7"